name = "fdown-telegram-bot"
main = "index.mjs" # හෝ ඔබේ entry file එක
compatibility_date = "2025-011-01" # වත්මන් දිනයට ආසන්න දිනයක් යොදන්න.

# ⚠️ මේක තමයි ප්‍රධාන වෙනස!
compatibility_flags = [
    "nodejs_compat" 
]

# අමතර Workers configuration තිබේ නම් ඒවා මෙතනට

# Workers Logs සහ Tracing සක්‍රීය කිරීම සඳහා
[observability]
enabled = true
