name = "facebookdownbot"
main = "dist/worker.js" 
compatibility_date = "2024-11-18" 
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"
watch_dir = "src"

[[kv_namespaces]]
binding = "USER_DATABASE"
id = "e32386263b3f447eae2685c169993e1a"

[observability]
enabled = true
